### ISSUE TITLE
Use "MovingTime" instead of "ElapsedTime" in challenges

### ISSUE THREAD

**Issue by saskim** [veloek/tevling#25]
In this activity I was pausing and resuming the activity many times and was not out running for 3,5 hour 😰
<img width="569" alt="image" src="https://github.com/veloek/tevling/assets/3215647/a12f3199-85a6-4bd1-8183-e575bbbb32d3">

**Comment by veloek** [comment]
This might cause some shuffling in the score boards, but I think it's more correct and something we should do 👍

**Comment by veloek** [comment]
Closed by 31646a859d1431c535eb94d9bc70b5bcf66705cc
